import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next JS Kitchen Sink | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU"
          crossOrigin="anonymous"
        ></link>
      </Head>

      <div className="container">
        <h1 className="display-4">Next JS Kitchen Sink</h1>
        <hr />
        <h2 className="display-6">Examples</h2>

        <ul className="nav flex-column">
          <li className="nav-item">
            <Link href="paging/basic">
              <a className="nav-link">Paging -&gt; Basic</a>
            </Link>
          </li>
        </ul>
      </div>
    </div>
  );
};

export default Home;
